---
title: "Documento de procesamiento y fundición de la base de datos"
author: "Daniel Miranda, Juan Carlos Castillo, Catalina Miranda & José Conejeros"
date: "`r format(Sys.time(), "%d/%m/%Y")"
output:
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
  html_document:
    df_print: paged
  word_document: default  
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(dev = 'jpg')
# remove all previous objects
rm(list = ls()) 
```

```{r global options, warning=FALSE, cache=FALSE, include=FALSE, results="asis"}
rm(list = ls()) #limpiar la memoria
#Desactivar notaci?n cient?fica
options(scipen=999)
#Paquetes
library(knitr)
library(DT)
library(plyr)
library(dplyr)
library(haven)
library(texreg) 
library(xtable) 
library(kableExtra) 
library(ggplot2)
library(psych)
library(purrr)
library(tidyr)
library(sjmisc)
library(Hmisc)
library(reshape)
library(VIM)
library(stringr)
library(skimr)
library(lme4)
library(broom)
library(survey)
library(srvyr)
```

```{r, include=FALSE}
#Directorio bases de datos AL
chi09 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/islchlc2.sas7bdat")
chi16 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2016/AL/islchlc3.sas7bdat")

mex09 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/islmexc2.sas7bdat")
mex16 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2016/AL/islmexc3.sas7bdat")


col09 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/islcolc2.sas7bdat")
col16 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2016/AL/islcolc3.sas7bdat")

dom09 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/isldomc2.sas7bdat")
dom16 <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2016/AL/isldomc3.sas7bdat")

gtm <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/islgtmc2.sas7bdat")
pry <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2009/AL/islpryc2.sas7bdat")
per <- read_sas("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism/Bases de datos/ICCS 2016/AL/islperc3.sas7bdat")

```


```{r, include=FALSE}
ruta<-setwd ("C:/Users/catac/Dropbox/F. Pap/Book_authoritarianism")