---
title: "Documento de resultados"
author: "Daniel Miranda, Juan Carlos Castillo, Catalina Miranda & José Conejeros"
date: "`r format(Sys.time(), "%d/%m/%Y")"
output:
  html_document:
    df_print: paged
---

```{r, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(dev = 'jpg')
# remove all previous objects
rm(list = ls()) 
```

```{r global options, warning=FALSE, cache=FALSE, include=FALSE, results="asis"}
rm(list = ls()) #limpiar la memoria
#Desactivar notaci?n cient?fica
options(scipen=999)
#Paquetes
library(knitr)
library(DT)
library(plyr)
library(dplyr)
library(haven)
library(texreg) 
library(xtable) 
library(kableExtra) 
library(ggplot2)
library(psych)
library(purrr)
library(tidyr)
library(sjmisc)
library(Hmisc)
library(reshape)
library(VIM)
library(stringr)
library(skimr)
library(lme4)
library(broom)
library(survey)
library(srvyr)
library(stargazer)
library(countrycode)
library(MplusAutomation)
```

# Base de datos

```{r}
#ICCS 2009: Latinamerica module. Merge two data-frames: 
#1. Test civic knowledge (ISL)
#2. Students questionary (ISG)

#Chile
chi09 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/islchlc2.sas7bdat"))
chi092 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isgchlc2.sas7bdat")) 
chi     <- merge(chi09, chi092, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Mexico
mex09 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/islmexc2.sas7bdat"))
mex092 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isgmexc2.sas7bdat"))
mex   <- merge(mex09, mex092, by="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Colombia
col09 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/islcolc2.sas7bdat"))
col092 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isgcolc2.sas7bdat"))
col   <- merge(col09, col092, by="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Paraguay
pry09 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/islpryc2.sas7bdat"))
pry092 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isgpryc2.sas7bdat"))
pry   <- merge(pry09, pry092, by="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Guatemala
gtm09 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/islgtmc2.sas7bdat"))
gtm092 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isggtmc2.sas7bdat"))
gtm   <- merge(gtm09, gtm092, by="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Domincan Republic
dom09 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isldomc2.sas7bdat"))
dom092 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2009/isgdomc2.sas7bdat"))
dom   <- merge(dom09, dom092, by="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Append: all obervations preserve
iccs09 <- rbind(chi, mex, col, pry, gtm, dom)
#class(iccs09)
#dim(iccs09)
#head(iccs09)
#str(iccs09)
#names(iccs09)
#dplyr::glimpse(iccs09) # general structure
#ICCS 2009
save(iccs09, file = "~/Dropbox/book_authoritarianism/Data/Analisis/ICCS09.Rdata")

########################################################
#ICCS 2016: Latinamerica module, student questionnaire
########################################################

#Chile
chi16 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/islchlc3.sas7bdat"))
chi162 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isgchlc3.sas7bdat"))
chi     <- merge(chi16, chi162, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#México
mex16 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/islmexc3.sas7bdat"))
mex162 <-  as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isgmexc3.sas7bdat"))
mex     <- merge(mex16, mex162, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Colombia
col16 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/islcolc3.sas7bdat"))
col162 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isgcolc3.sas7bdat"))
col     <- merge(col16, col162, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#República Dominicana
dom16 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isldomc3.sas7bdat"))
dom162 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isgdomc3.sas7bdat"))
dom     <- merge(dom16, dom162, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Perú
per16 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/islperc3.sas7bdat"))
per162 <- as.data.frame(read_sas("~/Dropbox/book_authoritarianism/Data/Original/2016/isgperc3.sas7bdat"))
per     <- merge(per16, per162, by ="IDSTUD", all=FALSE, suffixes = c("",".y"))#Merge
#Append: all obervations preserve
iccs16 <- rbind(chi, mex, col, dom, per)
#class(iccs16)
#dim(iccs16)
#head(iccs16)
#str(iccs116)
#names(iccs16)
#dplyr::glimpse(iccs16) # ver estructura general
#ICCS 2016
save(iccs16, file = "~/Dropbox/book_authoritarianism/Data/Analisis/ICCS16.Rdata")
```


```{r include=FALSE}
#rm(list = ls()) 
#Cargamos base de datos 
load("~/Dropbox/book_authoritarianism/Data/Analisis/ICCS09.Rdata")
load("~/Dropbox/book_authoritarianism/Data/Analisis/ICCS16.Rdata")
```


# Generación de variables 

```{r, echo=TRUE, eval=TRUE}
#Data frames with all variables
#2009
dict09 =  iccs09 %>%
  mutate(time          = 2009) %>%
  mutate(country       = COUNTRY) %>%
  mutate(idcountry     = IDCNTRY) %>%
  mutate(idschool       = IDSCHOOL) %>%
  mutate(idstudent     = IDSTUD) %>%
  mutate(idstudent = (time*1000000000000 + idcountry*100000000 + idstudent)) %>% #NEW IDSTUDENT
  mutate(dicta1         = 5-LS2P02A) %>% #Government leaders to make decisions without consulting anybody
  mutate(dicta2         = 5-LS2P02B) %>% #People in government must enforce their authority even
  mutate(dicta3         = 5-LS2P02C) %>% #People in government lose part of their authority
  mutate(dicta4         = 5-LS2P02D) %>% #People whose opinions are different must be considered its enemies
  mutate(dicta5         = 5-LS2P02E) %>% #The most important opinion of a country should be that of the pres
  mutate(dicta6         = 5-LS2P02F) %>% #It is fair that the government does not comply with the law
  mutate(dicta7         = 5-LS2P03A) %>% #It is fair that the government does not comply with the law
  mutate(dicta8         = 5-LS2P03B) %>% #Concentration of power in one person guarantees order
  mutate(dicta9         = 5-LS2P03C) %>% #If the president does not agree withCongress>, he should dissolve 
  mutate(dict_safety   = 5-LS2P03D) %>% #DICTATORSHIPS ARE JUSTIFIED WHEN THEY BRING ORDER AND SAFETY
  mutate(dict_benefits = 5-LS2P03E) %>% #DICTATORSHIPS ARE JUSTIFIED WHEN THEY BRING ECONOMIC BENEFITS
  mutate(dict          = (dict_safety + dict_benefits)/2) %>% #MEAN DIC
  mutate(pv1civ        = PV1CIV) %>%
  mutate(pv2civ        = PV2CIV) %>%
  mutate(pv3civ        = PV3CIV) %>%
  mutate(pv4civ        = PV4CIV) %>%
  mutate(pv5civ        = PV5CIV) %>%
  mutate(civic_knowledge = (pv1civ + pv2civ + pv3civ + pv4civ + pv5civ)/5) %>% #MEAN CIVIC KNOWLEDGE 
  mutate(s_intrust       = INTRUST) %>% #TRUST IN CIVIC INSTITUTIONS 
  mutate(s_opdisc        = OPDISC) %>%  #OPENNESS IN CLASS DISCUSSION
  mutate(s_hisced        = HISCED) %>%  #HIGHEST PARENTAL EDUCATIONAL LEVEL 
  mutate(univ            = ifelse(s_hisced>3, 1, 0)) %>% #UNIVERSITARY PARENTS
  mutate(s_hisei         = HISEI) %>%   #PARENT'S HIGHEST OCCUPATIONAL STATUS
  mutate(s_homelit       = HOMELIT) %>% #HOME LITERACY
  mutate(s_gender        = SGENDER) %>% #GENDER OF STUDENT
  mutate(s_age           = SAGE) %>%    #AGE STUDENT
  mutate(s_citcon        = CITCON) %>%  #CONVENTIONAL CITIZENSHIP
  mutate(s_citsoc        = CITSOC) %>%  #SOCIAL MOVEMENT REL. CITIZENSHIP
  mutate(s_citeff        = CITEFF) %>%  #CITIZENSHIP SELF-EFFICACY 
  mutate(s_cntatt        = ATTCNT) %>%  #ATTITUDES TOWARDS OWN COUNTRY 
  mutate(s_geneql        = GENEQL) %>%  #ATTITUDES TOWARDS GENDER EQUALITY
  mutate(s_ethrght       = ETHRGHT) %>% #EQUAL RIGHTS FOR ALL ETHNIC GROUPS 
  mutate(l_attviol       = ATTVIOL) %>% #ATTITUDES: USE OF VIOLENCE 
  mutate(l_attdiv        = ATTDIFF) %>% #ATTITUDES: NEIGHBOURHOOD DIVERSITY
  mutate(l_autgov        = AUTGOV) %>%  #AUTHORITARIANISM IN GOVERNMENT 
  mutate(l_attcorr       = ATTCORR) %>% #CORRUPT PRACTICES IN GOVERNMENT
  mutate(l_dislaw        = DISLAW) %>%  #ATTITUDES: DISOBEYING THE LAW
  mutate(l_empclas       = EMPATH) %>%  #EMPATHY TOWARDS CLASSMATES
  mutate(s_poldisc       = POLDISC) %>% #DISCUSSION OF POL. AND SOC. ISSUES
  #TRUST
  mutate(nac_gob       = 5 - IS2P27A) %>% #TRUST INSTITUTIONS-NATIONAL GOVERNMENT  
  mutate(local_gob     = 5 - IS2P27B) %>% #TRUST INSTITUTIONS-LOCAL GOVERNMENT 
  mutate(courts        = 5 - IS2P27C) %>% #TRUST INSTITUTIONS-COURTS
  mutate(police        = 5 - IS2P27D) %>% #TRUST INSTITUTIONS-POLICE 
  mutate(pol_parties   = 5 - IS2P27E) %>% #TRUST INSTITUTIONS-POLITICAL PARTIES
  mutate(parliament    = 5 - IS2P27F) %>% #TRUST INSTITUTIONS-PARLIAMENT
  mutate(media         = 5 - IS2P27G) %>% #TRUST INSTITUTIONS-MEDIA
  mutate(ffaa          = 5 - IS2P27H) %>% #TRUST INSTITUTIONS-FFAA 
  mutate(school        = 5 - IS2P27I) %>% #TRUST INSTITUTIONS-SCHOOL
  mutate(unit_nations  = 5 - IS2P27J) %>% #TRUST INSTITUTIONS-UNITED NATIONS 
  mutate(people        = 5 - IS2P27K) %>% #TRUST INSTITUTIONS-PEOPLE
  mutate(social          = NA) %>%   #TRUST INSTITUTIONS-SOCIAL MEDIA
  #WEITHINGS5 - 
  mutate(totwgts       = TOTWGTS) %>%   #FINAL STUDENT WEIGHT
  mutate(wgtfac1       = WGTFAC1) %>%   #SCHOOL BASE WEIGHT
  mutate(wgtadj1s      = WGTADJ1S) %>%  #SCHOOL WEIGHT ADJUSTMENT-STUDENT STUDY
  mutate(wgtfac2s      = WGTFAC2S) %>%  #CLASS WEIGHT FACTOR
  mutate(wgtadj2s      = WGTADJ2S) %>%  #CLASS WEIGHT ADJUSTMENT
  mutate(wgtadj3s      = WGTADJ3S) %>%  #STUDENT WEIGHT ADJUSTMENT
  mutate(jkzones       = JKZONES) %>%   #JACKKNIFE ZONE - STUDENT STUDY
  mutate(jkreps        = JKREPS)  %>%  #JACKKNIFE REPLICATE CODE
  select(411:474)
 
#2016  
dict16 = iccs16 %>%
  mutate(time            = 2016) %>%
  mutate(country         = COUNTRY) %>%
  mutate(idcountry       = IDCNTRY) %>%
  mutate(idschool        = IDSCHOOL) %>%
  mutate(idstudent       = IDSTUD) %>%
  mutate(idstudent       = (time*100000000000 + idcountry*100000000 + idstudent)) %>% #NEW IDSTUDENT
  mutate(dicta1         = 5-LS3G01A) %>% #Government leaders to make decisions without consulting anybody
  mutate(dicta2         = 5-LS3G01B) %>% #People in government must enforce their authority even
  mutate(dicta3         = 5-LS3G01C) %>% #People in government lose part of their authority
  mutate(dicta4         = 5-LS3G01D) %>% #People whose opinions are different must be considered its enemies
  mutate(dicta5         = 5-LS3G01E) %>% #The most important opinion of a country should be that of the pres
  mutate(dicta6         = 5-LS3G01F) %>% #It is fair that the government does not comply with the law
  mutate(dicta7         = 5-LS3G02A) %>% #It is fair that the government does not comply with the law
  mutate(dicta8         = 5-LS3G02B) %>% #Concentration of power in one person guarantees order
  mutate(dicta9         = 5-LS3G02C) %>% #If the president does not agree withCongress>, he should dissolve
  mutate(dict_safety     = 5-LS3G02D) %>% #DICTATORSHIPS ARE JUSTIFIED WHEN THEY BRING ORDER AND SAFETY
  mutate(dict_benefits   = 5-LS3G02E) %>% #DICTATORSHIPS ARE JUSTIFIED WHEN THEY BRING ECONOMIC BENEFITS
  mutate(dict          = (dict_safety + dict_benefits)/2) %>% 
  mutate(pv1civ          = PV1CIV) %>%
  mutate(pv2civ          = PV2CIV) %>%
  mutate(pv3civ          = PV3CIV) %>%
  mutate(pv4civ          = PV4CIV) %>%
  mutate(pv5civ          = PV5CIV) %>%
  mutate(civic_knowledge = (pv1civ + pv2civ + pv3civ + pv4civ + pv5civ)/5) %>% #MEAN CIVIC KNOWLEDGE 
  mutate(s_intrust       = S_INTRUST) %>% #TRUST IN CIVIC INSTITUTIONS 
  mutate(s_opdisc        = S_OPDISC) %>%  #OPENNESS IN CLASS DISCUSSION
  mutate(s_hisced        = S_HISCED) %>%  #HIGHEST PARENTAL EDUCATIONAL LEVEL 
  mutate(univ            = ifelse(s_hisced>3, 1, 0)) %>% #UNIVERSITARY PARENTS
  mutate(s_hisei         = S_HISEI) %>%   #PARENT'S HIGHEST OCCUPATIONAL STATUS
  mutate(s_homelit       = S_HOMLIT) %>%  #HOME LITERACY
  mutate(s_gender        = S_GENDER) %>%  #GENDER OF STUDENT
  mutate(s_age           = S_AGE) %>%     #AGE STUDENT
  mutate(s_citcon        = S_CITCON) %>%  #CONVENTIONAL CITIZENSHIP
  mutate(s_citsoc        = S_CITSOC) %>%  #SOCIAL MOVEMENT REL. CITIZENSHIP
  mutate(s_citeff        = S_CITEFF) %>%  #CITIZENSHIP SELF-EFFICACY 
  mutate(s_cntatt        = S_CNTATT) %>%  #ATTITUDES TOWARDS OWN COUNTRY 
  mutate(s_geneql        = S_GENEQL) %>%  #ATTITUDES TOWARDS GENDER EQUALITY
  mutate(s_ethrght       = S_ETHRGHT) %>% #EQUAL RIGHTS FOR ALL ETHNIC GROUPS 
  mutate(l_attviol       = L_ATTVIOL) %>% #ATTITUDES: USE OF VIOLENCE 
  mutate(l_attdiv        = L_ATTDIV) %>%  #ATTITUDES: NEIGHBOURHOOD DIVERSITY
  mutate(l_autgov        = L_AUTGOV) %>%  #AUTHORITARIANISM IN GOVERNMENT 
  mutate(l_attcorr       = L_ATTCORR) %>% #CORRUPT PRACTICES IN GOVERNMENT
  mutate(l_dislaw        = L_DISLAW) %>%  #ATTITUDES: DISOBEYING THE LAW
  mutate(l_empclas       = L_EMPCLAS) %>% #EMPATHY TOWARDS CLASSMATES
  mutate(s_poldisc       = S_POLDISC) %>% #DISCUSSION OF POL. AND SOC. ISSUES  
  #TRUST
  mutate(nac_gob         = 5 - IS3G26A) %>%   #TRUST INSTITUTIONS-NATIONAL GOVERNMENT 
  mutate(local_gob       = 5 - IS3G26B) %>%   #TRUST INSTITUTIONS-LOCAL GOVERNMENT 
  mutate(courts          = 5 - IS3G26C) %>%   #TRUST INSTITUTIONS-COURTS
  mutate(police          = 5 - IS3G26D) %>%   #TRUST INSTITUTIONS-POLICE
  mutate(pol_parties     = 5 - IS3G26E) %>%   #TRUST INSTITUTIONS-POLITICAL PARTIES
  mutate(parliament      = 5 - IS3G26F) %>%   #TRUST INSTITUTIONS-PARLIAMENT
  mutate(media           = 5 - IS3G26G) %>%   #TRUST INSTITUTIONS-MEDIA
  mutate(ffaa            = 5 - IS3G26I) %>%   #TRUST INSTITUTIONS-FFAA
  mutate(school          = 5 - IS3G26J) %>%   #TRUST INSTITUTIONS-SCHOOL
  mutate(unit_nations    = 5 - IS3G26K) %>%   #TRUST INSTITUTIONS-UNITED NATIONS
  mutate(people          = 5 - IS3G26L) %>%   #TRUST INSTITUTIONS-PEOPLE
  mutate(social          = 5 - IS3G26H) %>%   #TRUST INSTITUTIONS-SOCIAL MEDIA
  #WEITHINGS5 - 
  mutate(totwgts         = TOTWGTS) %>%   #FINAL STUDENT WEIGHT
  mutate(wgtfac1         = WGTFAC1) %>%   #SCHOOL BASE WEIGHT
  mutate(wgtadj1s        = WGTADJ1S) %>%  #SCHOOL WEIGHT ADJUSTMENT-STUDENT STUDY
  mutate(wgtfac2s        = WGTFAC2S) %>%  #CLASS WEIGHT FACTOR
  mutate(wgtadj2s        = WGTADJ2S) %>%  #CLASS WEIGHT ADJUSTMENT
  mutate(wgtadj3s        = WGTADJ3S) %>%  #STUDENT WEIGHT ADJUSTMENT
  mutate(jkzones         = JKZONES)  %>%  #JACKKNIFE ZONE - STUDENT STUDY
  mutate(jkreps          = JKREPS)  %>%  #JACKKNIFE REPLICATE CODE
  select(519:582)
#Merge data
mergeiccs <- full_join(dict09, dict16)
mergeiccs$ncountry <- countrycode(mergeiccs$country, 'iso3c', 'country.name') 
mergeiccs <- mergeiccs[, c(1:3,65,4:64)]
#All observations with complete row data
mergeiccs_miss <- mergeiccs[complete.cases(mergeiccs),]
```

+ Tamaño de la muestra

```{r, echo=TRUE, eval=TRUE}
#ICCS LA: 2009 - 2016
iccs_count <- mergeiccs %>% 
  group_by(time, ncountry) %>%
  dplyr::summarise(N=n(), man=mean(s_gender, na.rm=T), age=mean(s_age, na.rm=T)) %>%
  arrange(ncountry)
#ID School
iccs_count2 <- mergeiccs %>% 
  group_by(time, ncountry, idschool) %>%
  dplyr::summarise(n=n()) %>%
  dplyr::summarise(s=n()) %>%
  arrange(ncountry)
iccs_count$s <- iccs_count2$s 
rm(iccs_count2)
iccs_count$time <- as.character(iccs_count$time) 

#Table
print(xtable(iccs_count[, c(2:1,6,3:5)],  caption = "Sample", format="text"), include.rownames=FALSE)
```

+ Confianza en instituciones

```{r, echo=TRUE, eval=TRUE}


```


+ Apoyo a prácticas autoritarias 

```{r, echo=TRUE, eval=TRUE}
library(purrr)

aux09_i <- c("chi09", "mex09", "col09", "dom09","gtm", "pry","")
aux16_i <- c("chi16", "mex16", "col16", "dom16", "", "","per")
pais0_i <- c("CHL","MEX","COL","DOM","GTM","PRY","PER")
pais_i  <- c("CHI","MEX","COL","DOM","GTM","PRY","PER")

df_final <- NULL 

for(i in 1:7){
  
if(aux09_i[i]!="") {aux09 <- get(aux09_i[i])}
if(aux16_i[i]!="") {aux16 <- get(aux16_i[i])}
pais0 = pais0_i[i]
pais = pais_i[i]

aux09 <- aux09 %>% 
  mutate(dictaa = case_when(
    dict_safety %in% c(1,2) ~ 1,
    dict_safety %in% c(3,4) ~ 2,
    is.na(dicta1) ~ dict_safety,
    TRUE ~ 0
  )) %>% 
  mutate(dictab = case_when(
    dict_benefits %in% c(1,2) ~ 1,
    dict_benefits %in% c(3,4) ~ 2,
    is.na(dicta2) ~ dict_benefits,
    TRUE ~ 0
  )) 
aux16 <- aux16 %>% 
  mutate(dictaa = case_when(
    dict_safety %in% c(1,2) ~ 1,
    dict_safety %in% c(3,4) ~ 2,
    is.na(dicta1) ~ dict_safety,
    TRUE ~ 0
  )) %>% 
  mutate(dictab = case_when(
    dict_benefits%in% c(1,2) ~ 1,
    dict_benefits %in% c(3,4) ~ 2,
    is.na(dicta2) ~ dict_benefits,
    TRUE ~ 0
  )) 

if(aux09_i[i]!="" & aux16_i[i]!=""){ mergeiccs=full_join(aux16, aux09) }
if(aux09_i[i]!="" & aux16_i[i]==""){ mergeiccs= aux09 }
if(aux09_i[i]=="" & aux16_i[i]!=""){ mergeiccs= aux16 }

mergesvy <-  mergeiccs %>%
      filter(country==pais0) %>%
      as_survey_design(
      strata = jkzones, 
      weights = totwgts, 
      ids = jkreps, 
      nest = TRUE)

# frequency table via taylor series linearization
  table_freq_01 <- mergesvy %>%
    dplyr::group_by(time, dictaa) %>%
    summarize(proportion = survey_mean(,na.rm=TRUE))
  #help(srvyr)

  df = data.frame(table_freq_01, digits=2)

  df= df %>%
    mutate(perc = proportion * 100) %>%
    mutate(p=round(perc, 2)) %>%
    mutate(label=factor(dicta1, labels=c("Disagree", "Agree"))) %>% 
    mutate(country=pais)
  
  df1_aux <- df
  
  df_final <- rbind(df_final, df1_aux)
  
}

```


+ Conocimiento Cívico

```{r, echo=TRUE, eval=TRUE}

```


```

